name: ai_assistant
description: "AI Daily Assistant with Financial Tracking."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.10.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  flutter_animate: ^4.5.0
  # Gunakan versi yang disarankan oleh Flutter agar kompatibel
  lucide_icons: ^0.257.0
  google_fonts: ^6.2.1
  supabase_flutter: ^2.6.0 # Tambahkan ini
  google_generative_ai: ^0.4.0
  http: ^1.6.0
  flutter_markdown: ^0.7.7+1
  fl_chart: ^0.68.0
  intl: ^0.19.0
  image_picker: ^1.2.1
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # Tetap tanpa uses-material-3 jika masih error, atau biarkan kosong jika ragu
  assets:
    - assets/images/
